import '../../shared/models/app_enums.dart';
import '../../shared/models/track_seed_catalog.dart';

class SeedService {
  const SeedService();

  TrackSeedBundle catalog() {
    return TrackSeedBundle(
      tracks: const [
        TrackSeed(
          id: 'track-data-engineer',
          name: 'Data Engineer',
          description:
              'Pipelines, modelagem analítica, cloud data stack e governança.',
          iconKey: 'database',
          colorHex: '#005F73',
          roadmapSummary:
              'Fundamentos de SQL, orquestração, modelagem, cloud data warehouse e observabilidade.',
          skills: [
            SkillSeed(
              id: 'skill-de-sql',
              name: 'SQL Analítico',
              description: 'Consultas, CTEs, joins, tuning e modelagem.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-de-python',
              name: 'Python para Dados',
              description: 'ETL, APIs, testes e automações.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-de-orchestration',
              name: 'Orquestração',
              description: 'DAGs, jobs agendados e reprocessamento.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-de-cloud',
              name: 'Cloud Data',
              description: 'Storage, warehouse, IAM e custos.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-de-sql',
              title: 'SQL Profissional',
              summary: 'Domine SQL para engenharia e analytics.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-de-python-etl',
              title: 'ETL com Python',
              summary: 'Extração, transformação, testes e observabilidade.',
              estimatedHours: 22,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-de-airflow',
              title: 'Orquestração de Pipelines',
              summary: 'Airflow, retries, SLA e deploy.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-de-warehouse',
              title: 'Data Warehouse e Modelagem',
              summary: 'Star schema, particionamento e governança.',
              estimatedHours: 20,
              sortOrder: 4,
              isCore: true,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-backend-python',
          name: 'Backend Python',
          description:
              'APIs robustas, arquitetura, testes, filas e observabilidade.',
          iconKey: 'server',
          colorHex: '#2EC5FF',
          roadmapSummary:
              'HTTP, FastAPI/Django, bancos relacionais, filas, cache e deploy.',
          skills: [
            SkillSeed(
              id: 'skill-bpy-python',
              name: 'Python',
              description: 'Sintaxe, tipagem, testes e clean code.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bpy-api',
              name: 'APIs REST',
              description: 'Versionamento, autenticação e documentação.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bpy-db',
              name: 'Banco Relacional',
              description: 'SQL, ORM, migrations e performance.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bpy-ops',
              name: 'Deploy & Observabilidade',
              description: 'Logs, métricas, Docker e CI/CD.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bpy-foundations',
              title: 'Fundamentos Python',
              summary: 'Base sólida, typing e testes.',
              estimatedHours: 14,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bpy-fastapi',
              title: 'APIs com FastAPI',
              summary: 'Rotas, validação, auth e documentação.',
              estimatedHours: 20,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bpy-postgres',
              title: 'Persistência com Postgres',
              summary: 'Modelagem, migrations e queries.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bpy-background',
              title: 'Background Jobs e Deploy',
              summary: 'Filas, Docker, logging e deploy.',
              estimatedHours: 18,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-backend-php',
          name: 'Backend PHP',
          description:
              'Laravel moderno, APIs, filas, testes e aplicações de negócio.',
          iconKey: 'code',
          colorHex: '#FFC857',
          roadmapSummary:
              'PHP moderno, Laravel, arquitetura em camadas, filas e deploy.',
          skills: [
            SkillSeed(
              id: 'skill-bphp-php',
              name: 'PHP Moderno',
              description: 'POO, Composer, tipagem e boas práticas.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bphp-laravel',
              name: 'Laravel',
              description: 'Eloquent, jobs, events e auth.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bphp-sql',
              name: 'MySQL/Postgres',
              description: 'Queries, índices e tuning.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bphp-tests',
              name: 'Testes',
              description: 'Feature tests, unit tests e contratos.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bphp-core',
              title: 'Core PHP',
              summary: 'Base sólida com Composer e POO.',
              estimatedHours: 12,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bphp-laravel-api',
              title: 'Laravel API',
              summary: 'Controllers, resources, auth e filas.',
              estimatedHours: 22,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bphp-data',
              title: 'Persistência e Cache',
              summary: 'Migrations, cache e performance.',
              estimatedHours: 16,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bphp-ops',
              title: 'Deploy e Observabilidade',
              summary: 'CI/CD, Horizon, logs e monitoramento.',
              estimatedHours: 14,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-frontend-react',
          name: 'Front-end React',
          description:
              'Interfaces modernas, performance, componentização e testes.',
          iconKey: 'monitor',
          colorHex: '#35D39A',
          roadmapSummary:
              'HTML/CSS/JS, React, estado, design system e deploy front.',
          skills: [
            SkillSeed(
              id: 'skill-fr-react',
              name: 'React',
              description: 'Hooks, arquitetura e roteamento.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-fr-typescript',
              name: 'TypeScript',
              description: 'Tipos, inferência e modelagem.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-fr-ui',
              name: 'UI Engineering',
              description: 'Layout responsivo, acessibilidade e motion.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-fr-tests',
              name: 'Testes Front-end',
              description: 'Unitários, integração e e2e.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-fr-js-ts',
              title: 'JavaScript e TypeScript',
              summary: 'Base de linguagem para aplicações ricas.',
              estimatedHours: 18,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fr-react',
              title: 'React Profissional',
              summary: 'Hooks, estado e arquitetura.',
              estimatedHours: 24,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fr-design-system',
              title: 'Design System e UX',
              summary: 'Tokens, componentes e acessibilidade.',
              estimatedHours: 14,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fr-testing',
              title: 'Qualidade Front-end',
              summary: 'Testes, performance e monitoramento.',
              estimatedHours: 12,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-full-stack',
          name: 'Full Stack',
          description: 'Fluxo ponta a ponta com front, back, banco e deploy.',
          iconKey: 'layers',
          colorHex: '#005F73',
          roadmapSummary:
              'Base web, API, banco, autenticação, deploy e produto completo.',
          skills: [
            SkillSeed(
              id: 'skill-fs-front',
              name: 'Front-end',
              description: 'React, UI e consumo de APIs.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-fs-back',
              name: 'Back-end',
              description: 'APIs, auth e regras de negócio.',
              targetLevel: SkillLevel.junior,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-fs-db',
              name: 'Banco de Dados',
              description: 'Modelagem e queries eficientes.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-fs-product',
              name: 'Entrega de Produto',
              description: 'Deploy, feedback e evolução.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-fs-web',
              title: 'Fundamentos Web',
              summary: 'HTTP, HTML, CSS e JavaScript.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fs-app',
              title: 'Aplicação Completa',
              summary: 'Front-end, back-end e auth.',
              estimatedHours: 26,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fs-db',
              title: 'Persistência e Deploy',
              summary: 'Banco, Docker e publicação.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-fs-scale',
              title: 'Escala e Observabilidade',
              summary: 'Logs, métricas e iteração.',
              estimatedHours: 12,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-devops',
          name: 'DevOps',
          description:
              'Automação, infraestrutura, containers, pipelines e observabilidade.',
          iconKey: 'cloud',
          colorHex: '#2EC5FF',
          roadmapSummary: 'Linux, redes, Docker, CI/CD, cloud e monitoramento.',
          skills: [
            SkillSeed(
              id: 'skill-do-linux',
              name: 'Linux & Shell',
              description: 'Base operacional e automação.',
              targetLevel: SkillLevel.junior,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-do-docker',
              name: 'Containers',
              description: 'Docker, registries e imagens.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-do-cicd',
              name: 'CI/CD',
              description: 'Pipelines, quality gates e deploy.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-do-observability',
              name: 'Observabilidade',
              description: 'Logs, métricas, tracing e alertas.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-do-linux',
              title: 'Linux e Redes',
              summary: 'Base operacional para ambiente real.',
              estimatedHours: 14,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-do-docker',
              title: 'Docker e Containers',
              summary: 'Imagens, compose e boas práticas.',
              estimatedHours: 18,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-do-cicd',
              title: 'Pipelines CI/CD',
              summary: 'Automação de build, testes e deploy.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-do-cloud',
              title: 'Cloud e Observabilidade',
              summary: 'Infra básica, monitoramento e custos.',
              estimatedHours: 20,
              sortOrder: 4,
              isCore: true,
            ),
          ],
        ),
        TrackSeed(
          id: 'track-bi-analyst',
          name: 'BI / Data Analyst',
          description:
              'Análise, métricas, visualização, storytelling e produto.',
          iconKey: 'chart',
          colorHex: '#FFC857',
          roadmapSummary:
              'SQL, métricas, dashboards, estatística aplicada e storytelling.',
          skills: [
            SkillSeed(
              id: 'skill-bi-sql',
              name: 'SQL',
              description: 'Consultas, janelas e limpeza de dados.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 1,
            ),
            SkillSeed(
              id: 'skill-bi-metrics',
              name: 'Métricas',
              description: 'KPIs, funis e análise de negócio.',
              targetLevel: SkillLevel.midLevel,
              sortOrder: 2,
            ),
            SkillSeed(
              id: 'skill-bi-viz',
              name: 'Visualização',
              description: 'Dashboards claros e tomada de decisão.',
              targetLevel: SkillLevel.junior,
              sortOrder: 3,
            ),
            SkillSeed(
              id: 'skill-bi-storytelling',
              name: 'Storytelling',
              description: 'Comunicação executiva e insight acionável.',
              targetLevel: SkillLevel.junior,
              sortOrder: 4,
            ),
          ],
          modules: [
            ModuleSeed(
              id: 'module-bi-sql',
              title: 'SQL para Analytics',
              summary: 'Transformações, KPIs e camadas semânticas.',
              estimatedHours: 16,
              sortOrder: 1,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bi-metrics',
              title: 'Métricas de Produto e Negócio',
              summary: 'Definição, interpretação e análise.',
              estimatedHours: 14,
              sortOrder: 2,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bi-dashboard',
              title: 'Dashboards Executivos',
              summary: 'Visualização, narrativa e decisões.',
              estimatedHours: 18,
              sortOrder: 3,
              isCore: true,
            ),
            ModuleSeed(
              id: 'module-bi-case',
              title: 'Case Analítico',
              summary: 'Projeto fim a fim orientado a negócio.',
              estimatedHours: 16,
              sortOrder: 4,
              isCore: false,
            ),
          ],
        ),
      ],
    );
  }
}
